### PR TITLE
Updated To Mutter47 (libmutter-15)

### PR DESCRIPTION
**Pull request by travrei**
I use some files from [gala](https://github.com/elementary/gala/pull/2090/files), and the wingpannel builds, with the new version!!

### CODE REVIEW

**Comment by ryonakano** [comment]
@travrei Thank you for your contribution! I added additional fixes to your branch so that all CI passes :bow:

**Comment by travrei** [comment]
> @travrei Thank you for your contribution! I added additional fixes to your branch so that all CI passes 🙇

I'm glad to help! I hope to learn more about programming soon to help even more with elementary projects!! 🤓

**Review by tintou — APPROVED** [review]
Looks good to me!

**Comment by JPLeBreton** [comment]
Would it be possible to get a new release out (8.0.2?) with this fix? It would allow various other distros (eg Arch) to run pantheon + wayland on systems that also have gnome installed - currently the required mutter versions conflict.

**Comment by ryonakano** [comment]
@JPLeBreton We're sorry for your inconvenient and thank you for letting us know that. I opened #599 so it should be released soon.

**Comment by JPLeBreton** [comment]
Thank you! If the release notes for 8.0.2 mentioned that mutter47 is now supported that would make it clearer to downstream distros that it will (should?) work alongside the latest version of gnome.

**Pull request merged**
