### PR TITLE
Switch workspace when scrolling on the panel

### LINKED ISSUE #524: Mouse wheel scroll when hovering wingpanel switches workspaces
### Problem

Switching workspaces has long been a great power user feature, but isn't currently super well-exposed. Keyboard-heavy navigators can bind shortcuts to switch workspaces, but if your hand is already on the mouse, this proposal would frequently be more convenient.
Binding screen corner actions to workspace switching has the usual potential downsides, whereas currently mousewheel does nothing when the cursor is over the wingpanel.

### Proposal

When hovering the mouse over the wingpanel, mousewheel up and down navigate to higher and lower number workspaces, respectively. That's about it, really.

This behavior wouldn't even need to be on by default to still be useful a certain % of users who might appreciate it.

### Prior Art (Optional)

Numerous Gnome Shell extensions over the years have provided this feature, eg https://github.com/sunwxg/gnome-shell-extension-panelScroll

### PR DESCRIPTION
**Pull request by leolost2605**
Fixes #524

### CODE REVIEW

**Comment by lenemter** [comment]
I think you forgot to add Services/WMDBus.vala file to git here :sweat_smile:

**Review by danirabbit — CHANGES_REQUESTED** [review]
Hm, I can see the utility here but I think we probably need an off-by-default gsetting for this. I can already here the reports of folks triggering this by accident and thinking this is a bug since there's no visual indicator and there's nothing else workspace related in the panel

**Comment by leolost2605** [comment]
> I think you forgot to add Services/WMDBus.vala file to git here 😅

Whoops added it :)

> Hm, I can see the utility here but I think we probably need an off-by-default gsetting for this. I can already here the reports of folks triggering this by accident and thinking this is a bug since there's no visual indicator and there's nothing else workspace related in the panel

Sure we can do that

**Comment by leolost2605** [comment]
Should we expose it in settings?

**Comment by leolost2605** [comment]
Proposed the setting at elementary/switchboard-plug-pantheon-shell#416 :)

**Comment by leolost2605** [comment]
For a better experience I also opened elementary/wingpanel-indicator-power#264

**Review by danirabbit — APPROVED** [review]
Works for me! Cool feature :)

**Comment by JPLeBreton** [comment]
Thanks so much for implementing this! ❤️

**Pull request merged**
