### PR TITLE
PanelWindow: divide dimensions by scale on Wayland

### LINKED ISSUE #562: Most indicators missing on Wayland
### What Happened?

After upgrading my system, most indicators are missing on the Wayland session, only the calendar remains.

### Steps to Reproduce

1. Upgrade elementary
2. Login to the Wayland session
3. All the indicators are gone

### Expected Behavior

The indicators should be visible, particularly the power related ones

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Log Output

_No response_

### Hardware Info

Intel system with an AMD RX7600 GPU installed

### PR DESCRIPTION
**Pull request by danirabbit**
Fixes #562 

Test panel size on:
- [x] HiDPI with Wayland
- [x] LoDPI with Wayland
- [x] HiDPI with X11
- [x] LoDPI with X11

### CODE REVIEW

**Comment by danirabbit** [comment]
Can't test on X11 because of #564 :(

**Comment by leolost2605** [comment]
It seems this is only needed when fractional scaling is disabled (since it does logical layout instead of physical). Otherwise it will reintroduce the issue fixed in #559. Maybe we can do it depending on whether it's enabled?

**Comment by danirabbit** [comment]
@leolost2605 ah is there a simple way to test for that?

**Comment by leolost2605** [comment]
Hmm I dug a bit through gtk api but I only found stuff for GTK4 so I was kinda hoping somebody else knew something. I'll prepare a branch where we ask mutter via dbus :)

**Comment by danirabbit** [comment]
Closing since you proposed a better branch

**Pull request closed without merging**
