### PR TITLE
Application: hard code elementary styles

### PR DESCRIPTION
**Pull request by danirabbit**
Make sure people can't break styles even if they try to change the system stylesheet or icons

### CODE REVIEW

**Review by zeebok — APPROVED** [review]

**Comment by DimasKunJ** [comment]
how do i use another theme?. i don't really like the default theme. I can't change it and also can't downgrade.

**Comment by danirabbit** [comment]
@DimasKunJ We don't support changing the system style sheet. It's required to avoid buggy behavior

**Comment by rdanter** [comment]
I love elementaryOS, but some of the icons are not good nor even consistent with others. Could you at least make it possible to change icons? Perhaps with an "expert" mode or something to prevent people doing it accidentality?

**Comment by danirabbit** [comment]
@rdanter if you have an issue with one of the icons please report it at https://github.com/elementary/icons

If you'd like to request a new feature in the panel please open a new issue report here.

Closed pull requests are not a great place to try to have discussion 

Thanks!

**Pull request merged**
