### PR TITLE
Fix focus on dialogs started from wingpanel

### PR DESCRIPTION
**Pull request by peteruithoven**
Fixes: #228

### CODE REVIEW

**Comment by peteruithoven** [comment]
@cassidyjames did you also restart Gala after compiling an restarting wingpanel? (This logic depends on a Gala plugin)

**Comment by cassidyjames** [comment]
@peteruithoven hm, I did not since this looked self-contained within the panel. I'll reboot and continue testing :+1:

**Comment by peteruithoven** [comment]
If you don't want to restart you can also execute `gala -r` from the Applications Menu.

**Comment by cassidyjames** [comment]
@peteruithoven I know, but I figured I'd be safe and restart _everything._ :wink: Now it appears to properly retain focus, but _too_ well: closing the dialog keeps the focus on WingPanel instead of returning it to the previous app. :sweat_smile:

**Comment by peteruithoven** [comment]
Wingpanel && focus is such a nightmare... It stores the `last_focused_window` to restore focus to later on, in this case that became the dialog, which means there is no more record of the previously stored focused window. We'd need to add some kind of exception in probably the FocusManager. Figure out where we want to trigger this manual refocus from when the dialog is closed.

**Comment by peteruithoven** [comment]
I've added an exceptions for windows that are dialogs, making sure we don't lose the last focused window. When the wingpanel requests to restore focus it focuses this dialog and when the dialog is closed it focuses the last focused (non dialog) window.

**Comment by jeremypw** [comment]
Works as expected on dialogs - but not popovers (but I guess that is a different issue).

**Pull request merged**
